# Generated by Django 3.0.8 on 2020-07-26 22:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200720_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='brief',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
