# Generated by Django 3.0.8 on 2020-07-20 21:08

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('category_parent', models.ForeignKey(blank=True, limit_choices_to={'category_parent__isnull': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.Category', verbose_name='category_parent')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', ckeditor.fields.RichTextField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='main_product/', verbose_name='Image')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created Date')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Slug')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServiceImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='service/', verbose_name='Service Image')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.Service', verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Service Image',
                'verbose_name_plural': 'Service Images',
            },
        ),
    ]
