# Generated by Django 3.0.8 on 2020-07-26 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='album',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='album',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='alt',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='height',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='albumimage',
            name='width',
        ),
        migrations.AddField(
            model_name='album',
            name='albums_covers',
            field=models.FileField(default='albums_covers/def.png', upload_to='albums_covers/'),
        ),
        migrations.AddField(
            model_name='albumimage',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='image',
            field=models.FileField(default='albums/def.png', upload_to='albums/'),
        ),
    ]
